/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matematica_discreta_i;

/**
 *
 * @author Pedro
 */
public class Tabela_Verdade extends javax.swing.JFrame {

    /**
     * Creates new form Tabela_Verdade
     */
    
    private String expressao = "";
    String ultimoInput = "";
    public Tabela_Verdade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        expressaoTextField = new javax.swing.JTextField();
        ButtonP = new javax.swing.JButton();
        ButtonQ = new javax.swing.JButton();
        ButtonR = new javax.swing.JButton();
        ButtonS = new javax.swing.JButton();
        ButtonAND = new javax.swing.JButton();
        ButtonOR = new javax.swing.JButton();
        ButtonNOT = new javax.swing.JButton();
        ButtonImplication = new javax.swing.JButton();
        ButtonEquivalence = new javax.swing.JButton();
        ButtonOpen = new javax.swing.JButton();
        ButtonClose = new javax.swing.JButton();
        ButtonXOR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ButtonApagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        expressaoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressaoTextFieldActionPerformed(evt);
            }
        });

        ButtonP.setText("P");
        ButtonP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPActionPerformed(evt);
            }
        });

        ButtonQ.setText("Q");
        ButtonQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonQActionPerformed(evt);
            }
        });

        ButtonR.setText("R");
        ButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRActionPerformed(evt);
            }
        });

        ButtonS.setText("S");
        ButtonS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSActionPerformed(evt);
            }
        });

        ButtonAND.setText("^");
        ButtonAND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonANDActionPerformed(evt);
            }
        });

        ButtonOR.setText("v");
        ButtonOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonORActionPerformed(evt);
            }
        });

        ButtonNOT.setText("~");
        ButtonNOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNOTActionPerformed(evt);
            }
        });

        ButtonImplication.setText("->");
        ButtonImplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonImplicationActionPerformed(evt);
            }
        });

        ButtonEquivalence.setText("<->");
        ButtonEquivalence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEquivalenceActionPerformed(evt);
            }
        });

        ButtonOpen.setText("(");
        ButtonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOpenActionPerformed(evt);
            }
        });

        ButtonClose.setText(")");
        ButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCloseActionPerformed(evt);
            }
        });

        ButtonXOR.setText("⊻");
        ButtonXOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonXORActionPerformed(evt);
            }
        });

        jLabel1.setText("Regras:");

        jLabel2.setText("1 - ");

        jLabel3.setText("Sentenças:");

        jLabel4.setText("Conectivos: ");

        jLabel5.setText("Expressão:");

        ButtonApagar.setText("Apagar");
        ButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonApagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ButtonP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonS, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonApagar))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ButtonNOT)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ButtonAND)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ButtonOR)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ButtonXOR)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ButtonImplication)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ButtonEquivalence)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ButtonOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ButtonClose))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(expressaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonNOT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonAND)
                    .addComponent(ButtonOR)
                    .addComponent(ButtonXOR)
                    .addComponent(ButtonImplication)
                    .addComponent(ButtonEquivalence)
                    .addComponent(ButtonOpen)
                    .addComponent(ButtonClose)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expressaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ButtonApagar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonQ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void expressaoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressaoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressaoTextFieldActionPerformed

    private void ButtonPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPActionPerformed
        
        if (!ultimoInput.equals(")") && !ultimoInput.equals("P") && !ultimoInput.equals("Q") && !ultimoInput.equals("R") && !ultimoInput.equals("S")){
            expressao += "P";
            expressaoTextField.setText(expressao); 
            ultimoInput = "P";
        }
       
    }//GEN-LAST:event_ButtonPActionPerformed

    private void ButtonQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonQActionPerformed
	
		if (!ultimoInput.equals(")") && !ultimoInput.equals("P") && !ultimoInput.equals("Q") && !ultimoInput.equals("R") && !ultimoInput.equals("S")){
			expressao += "Q";
			expressaoTextField.setText(expressao);
			ultimoInput = "Q";
		}
		
    }//GEN-LAST:event_ButtonQActionPerformed

    private void ButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRActionPerformed
        
		if (!ultimoInput.equals(")") && !ultimoInput.equals("P") && !ultimoInput.equals("Q") && !ultimoInput.equals("R") && !ultimoInput.equals("S")){
			expressao += "R";
			expressaoTextField.setText(expressao);
			ultimoInput = "R";
		}
		
    }//GEN-LAST:event_ButtonRActionPerformed

    private void ButtonSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSActionPerformed
        
		if (!ultimoInput.equals(")") && !ultimoInput.equals("P") && !ultimoInput.equals("Q") && !ultimoInput.equals("R") && !ultimoInput.equals("S")){
			expressao += "S";
			expressaoTextField.setText(expressao);
			ultimoInput = "S";
		}
		
    }//GEN-LAST:event_ButtonSActionPerformed

    private void ButtonNOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNOTActionPerformed
       
	   if (!ultimoInput.equals(")") && !ultimoInput.equals("P") && !ultimoInput.equals("Q") && !ultimoInput.equals("R") && !ultimoInput.equals("S") && !ultimoInput.equals("~")){
			expressao += "~";
			expressaoTextField.setText(expressao);
			ultimoInput = "~";
		}
		
    }//GEN-LAST:event_ButtonNOTActionPerformed

    private void ButtonANDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonANDActionPerformed
	
        if (!ultimoInput.equals("(") && !ultimoInput.equals("^") && !ultimoInput.equals("v") &&  !ultimoInput.equals("~") && !ultimoInput.equals("⊻") && !ultimoInput.equals("->") && !ultimoInput.equals("<-->") ){
            expressao += "^";
            expressaoTextField.setText(expressao);
            ultimoInput = "^";
        }
        
    }//GEN-LAST:event_ButtonANDActionPerformed

    private void ButtonORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonORActionPerformed
        
		if (!ultimoInput.equals("(") && !ultimoInput.equals("^") && !ultimoInput.equals("v") && !ultimoInput.equals("~") && !ultimoInput.equals("⊻") && !ultimoInput.equals("->") && !ultimoInput.equals("<-->") ){
            expressao += "v";
            expressaoTextField.setText(expressao);
            ultimoInput = "v";
        }
		
    }//GEN-LAST:event_ButtonORActionPerformed

    private void ButtonXORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonXORActionPerformed
        
		if (!ultimoInput.equals("(") && !ultimoInput.equals("^") && !ultimoInput.equals("v") && !ultimoInput.equals("~") && !ultimoInput.equals("⊻") && !ultimoInput.equals("->") && !ultimoInput.equals("<-->") ){
            expressao += "⊻";
            expressaoTextField.setText(expressao);
            ultimoInput = "⊻";
        }
		
    }//GEN-LAST:event_ButtonXORActionPerformed

    private void ButtonImplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonImplicationActionPerformed
        
		if (!ultimoInput.equals("(") && !ultimoInput.equals("^") && !ultimoInput.equals("v") && !ultimoInput.equals("~") && !ultimoInput.equals("⊻") && !ultimoInput.equals("->") && !ultimoInput.equals("<-->") ){
            expressao += "->";
            expressaoTextField.setText(expressao);
            ultimoInput = "->";
        }
		
    }//GEN-LAST:event_ButtonImplicationActionPerformed

    private void ButtonEquivalenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEquivalenceActionPerformed
        
		if (!ultimoInput.equals("(") && !ultimoInput.equals("^") && !ultimoInput.equals("v") && !ultimoInput.equals("~") && !ultimoInput.equals("⊻") && !ultimoInput.equals("->") && !ultimoInput.equals("<-->") ){
            expressao += "<-->";
            expressaoTextField.setText(expressao);
            ultimoInput = "<-->";
        }
		
    }//GEN-LAST:event_ButtonEquivalenceActionPerformed

    private void ButtonOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOpenActionPerformed
        	if (!ultimoInput.equals("P") && !ultimoInput.equals("Q") && !ultimoInput.equals("R") && !ultimoInput.equals("S")){
                    expressao += "(";
                    expressaoTextField.setText(expressao);
                    ultimoInput = "(";
		}
    }//GEN-LAST:event_ButtonOpenActionPerformed

    private void ButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCloseActionPerformed
	if (!ultimoInput.equals("^") && !ultimoInput.equals("v") && !ultimoInput.equals("~") && !ultimoInput.equals("⊻") && !ultimoInput.equals("->") && !ultimoInput.equals("<-->") ){
            expressao += ")";
            expressaoTextField.setText(expressao);
            ultimoInput = ")";
	}
    }//GEN-LAST:event_ButtonCloseActionPerformed

    private void ButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonApagarActionPerformed
        ultimoInput = "";
        expressao = "";
        expressaoTextField.setText(expressao);
    }//GEN-LAST:event_ButtonApagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabela_Verdade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabela_Verdade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabela_Verdade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabela_Verdade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabela_Verdade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAND;
    private javax.swing.JButton ButtonApagar;
    private javax.swing.JButton ButtonClose;
    private javax.swing.JButton ButtonEquivalence;
    private javax.swing.JButton ButtonImplication;
    private javax.swing.JButton ButtonNOT;
    private javax.swing.JButton ButtonOR;
    private javax.swing.JButton ButtonOpen;
    private javax.swing.JButton ButtonP;
    private javax.swing.JButton ButtonQ;
    private javax.swing.JButton ButtonR;
    private javax.swing.JButton ButtonS;
    private javax.swing.JButton ButtonXOR;
    private javax.swing.JTextField expressaoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
